const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const c={};vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/race-core.js','utf8'),c);
const Race=c.SwimRace.Race;function make(n=16){const r=new Race(()=>.2);for(let i=0;i<n;i++)r.join('p'+i,i);return r;}function go(r){r.start();for(let i=0;i<31;i++)r.update(.1);assert.equal(r.phase,'race');}
test('needs two, caps at sixteen and makes up to four balanced lanes',()=>{const solo=make(1);assert.equal(solo.start(),false);for(let n=2;n<=16;n++){const r=make(n);assert.equal(r.start(),true);assert.equal(r.teams.length,Math.min(n,4));assert.ok(r.teams.every(t=>t.members.length<=4));assert.equal(r.join('extra',1).ok,false);}assert.equal(make().join('extra',1).ok,false)});
test('teammates propel absent swimmer and retain credits through relay',()=>{const r=make();go(r);const t=r.teams[0],first=r.active(t),next=t.members[1];assert.equal(r.tap(next.user,30),true);t.distance=599;r.update(.1);r.update(.1);assert.equal(t.stage,1);assert.equal(r.tap(first.user,20),true);assert.ok(t.relayUntil>r.time);assert.ok(next.credits>0);const before=t.distance;for(let i=0;i<25;i++)r.update(.1);assert.ok(t.distance>before);assert.equal(first.taps,20);assert.equal(next.taps,30)});
test('three finishers automatically place inactive fourth last',()=>{const r=make(4);go(r);for(let i=0;i<3;i++){const t=r.teams[i];t.distance=2399;r.tap(r.active(t).user,1);r.update(.1);r.update(.1);}assert.equal(r.phase,'finished');assert.equal(r.order.length,4);assert.equal(r.teams[3].place,4);assert.equal(r.teams[3].autoLast,true);assert.equal(r.teams[3].distance,0);assert.equal(r.events.filter(e=>e.type==='victory').length,1)});
test('damage never eliminates and slows down; specials hit a random rival',()=>{const r=make(2);go(r);const a=r.teams[0],b=r.teams[1],pa=r.active(a),pb=r.active(b);pa.sp=100;pb.hp=16;r.update(.1);assert.equal(pb.hp,15);r.tap(pa.user,1);r.tap(pb.user,1);r.update(.1);r.update(.1);assert.ok(a.distance>b.distance);assert.ok(r.events.some(e=>e.type==='special'&&e.to===b.id))});
test('lobby gifts pool in team; roses and corn wait; boosts consume sequentially',()=>{const r=make();r.players.forEach(p=>p.sp=100);r.gift('p0','rose',2);r.gift('p0','corn',2);r.gift('p0','popular',2);go(r);const t=r.teams.find(t=>t.members.some(p=>p.user==='p0')),p=r.active(t);p.sp=100;r.update(.1);assert.equal(t.stock.rose,2);assert.equal(t.stock.popular,1);p.hp=50;p.sp=50;r.update(.1);assert.equal(p.hp,80);assert.equal(t.stock.rose,1);assert.equal(t.stock.corn,1);assert.ok(p.sp<=100);r.update(.1);assert.equal(t.stock.popular,1)});
test('each team always runs 2400 meters and winner freezes race',()=>{const r=make(3);go(r);const t=r.teams[1];t.distance=2399;r.tap(r.active(t).user,1);r.update(.1);r.update(.1);assert.equal(t.distance,2400);assert.equal(r.phase,'race');assert.equal(r.winner,1);const before=t.distance;r.update(.1);assert.equal(t.distance,before)});
test('complete simulated relay race reaches finish without stranded teams',()=>{const r=make();go(r);for(let i=0;i<6000&&r.phase==='race';i++){for(const t of r.teams)r.tap(r.active(t).user,1);r.update(.1);}assert.equal(r.phase,'finished');assert.equal(r.teams[r.winner].distance,2400);assert.equal(r.teams[r.winner].stage,3);});
test('only water can join when the race has a species allowlist',()=>{const r=new Race(Math.random,[3,4]);assert.equal(r.join('ana',1).ok,false);assert.equal(r.join('ana',3).ok,true)});
