"""Install an opt-in music capture hook; inactive in normal play."""
from pathlib import Path
import argparse

HOOK = r'''

/* Stadiumfei: opt-in, game-thread music capture from the local ROM. */
extern void func_8004B1CC(uint8_t*, recomp_context*);
extern void func_8004B9C4(uint8_t*, recomp_context*);
extern void func_8004D9B0(uint8_t*, recomp_context*);
extern void func_8004B154(uint8_t*, recomp_context*);
static int stadiumfei_capture_dispatch = 0;
int stadiumfei_capture_muted(void) {
    const char* path=getenv("STADIUMFEI_MUSIC_REQUEST");
    return path && *path && !stadiumfei_capture_dispatch;
}
void stadiumfei_capture_music(uint8_t* rdram, recomp_context* ctx) {
    const char* path = getenv("STADIUMFEI_MUSIC_REQUEST");
    static unsigned long last = 0;
    unsigned long serial = 0;
    int song = -1;
    FILE* file;
    if (!path || !*path) return;
    if (!MEM_LOAD_BE32(rdram, 0xFC6E4)) return;
    file = fopen(path, "r");
    if (!file) return;
    int count = fscanf(file, "%lu %d", &serial, &song);
    fclose(file);
    if (count != 2 || serial == last || song < -1 || (song > 79 && (song < 0x20001 || song > 0x2000A))) return;
    last = serial;
    recomp_context saved = *ctx;
    /* Injected callees write their argument home area at the caller's SP.
       Preserve it because the interrupted function has not made its frame. */
    uint8_t home[32];
    uint32_t sp = (uint32_t)ctx->r29 & 0xFFFFFF;
    memcpy(home, rdram + sp, sizeof(home));
    stadiumfei_capture_dispatch = 1;
    func_8004B154(rdram, ctx);
    if (song == -1 || song > 79) {
        ctx->r4 = 1;
        func_8004B9C4(rdram, ctx);
    }
    if (song >= 0 && song <= 79) {
        ctx->r4 = song;
        func_8004B1CC(rdram, ctx);
    } else if (song > 79) {
        /* Scene initialization can replace the SFX bank while leaving its
           cached ID unchanged. Always reload our requested original bank. */
        MEM_W(0, 0x80079014) = 0;
        ctx->r4 = song; ctx->r5 = 1; ctx->r6 = 4;
        func_8004D9B0(rdram, ctx);
    }
    *ctx = saved;
    memcpy(rdram + sp, home, sizeof(home));
    stadiumfei_capture_dispatch = 0;
    fprintf(stderr, "[Stadiumfei music] serial=%lu song=%d\n", serial, song);
    fflush(stderr);
}
'''
PATCH = '''

# Stadiumfei local music capture; disabled unless its environment variable is set.
[[patches.hook]]
func = "func_80006FE8"
before_vram = 0x80006FE8
text = "extern void stadiumfei_capture_music(uint8_t*, recomp_context*); stadiumfei_capture_music(rdram, ctx);"
'''

def main():
    p=argparse.ArgumentParser();p.add_argument('port',type=Path);a=p.parse_args()
    for name,addition in [('extras.c',HOOK),('game.toml',PATCH)]:
        path=a.port/name;text=path.read_text(encoding='utf-8')
        if name=='extras.c' and '/* Stadiumfei: opt-in, game-thread music capture' in text:
            text=text.split('/* Stadiumfei: opt-in, game-thread music capture')[0].rstrip()+addition
            path.write_text(text,encoding='utf-8')
        elif 'stadiumfei_capture_music' not in text:path.write_text(text+addition,encoding='utf-8')
    # Existing generated sources are not regenerated by CMake. Apply the same
    # entry hook there, without recompiling every unaffected function group.
    marker='RECOMP_FUNC void func_80006FE8(uint8_t* rdram, recomp_context* ctx) {'
    for path in (a.port/'generated').glob('funcs_*.c'):
        text=path.read_text(encoding='utf-8')
        if marker in text and 'stadiumfei_capture_music' not in text:
            text=text.replace(marker,marker+'\n    extern void stadiumfei_capture_music(uint8_t*, recomp_context*);\n    stadiumfei_capture_music(rdram, ctx);',1)
            path.write_text(text,encoding='utf-8')
    print('Hook instalado. Compila el port; solo se activa durante Capturar-musica.ps1.')
    # Prevent attract-mode scenes from mixing unrelated music or effects into
    # the take. These guards are inactive when the capture env var is absent.
    config=a.port/'game.toml'
    for function in ['func_8004B1CC','func_8004D9B0','func_8004B094','func_8004B9C4']:
        gate='extern int stadiumfei_capture_muted(void); if (stadiumfei_capture_muted()) return;'
        entry=f'RECOMP_FUNC void {function}(uint8_t* rdram, recomp_context* ctx) {{'
        for path in (a.port/'generated').glob('funcs_*.c'):
            text=path.read_text(encoding='utf-8')
            if entry in text and entry+'\n    '+gate not in text:
                path.write_text(text.replace(entry,entry+'\n    '+gate,1),encoding='utf-8')
        text=config.read_text(encoding='utf-8')
        marker=f'# Stadiumfei capture gate {function}'
        if marker not in text:
            config.write_text(text+f'\n{marker}\n[[patches.hook]]\nfunc = "{function}"\nbefore_vram = 0x{function[5:]}\ntext = "{gate}"\n',encoding='utf-8')

if __name__=='__main__':main()
