"""Install an opt-in music capture hook; inactive in normal play."""
from pathlib import Path
import argparse

HOOK = r'''

/* Stadiumfei: opt-in, game-thread music capture from the local ROM. */
extern void func_8004B1CC(uint8_t*, recomp_context*);
void stadiumfei_capture_music(uint8_t* rdram, recomp_context* ctx) {
    const char* path = getenv("STADIUMFEI_MUSIC_REQUEST");
    static unsigned long last = 0;
    unsigned long serial = 0;
    int song = -1;
    FILE* file;
    if (!path || !*path) return;
    if (!MEM_LOAD_BE32(rdram, 0xFC6E4)) return;
    file = fopen(path, "r");
    if (!file) return;
    int count = fscanf(file, "%lu %d", &serial, &song);
    fclose(file);
    if (count != 2 || serial == last || song < 0 || song > 79) return;
    last = serial;
    recomp_context saved = *ctx;
    ctx->r4 = song;
    func_8004B1CC(rdram, ctx);
    *ctx = saved;
    fprintf(stderr, "[Stadiumfei music] serial=%lu song=%d\n", serial, song);
    fflush(stderr);
}
'''
PATCH = '''

# Stadiumfei local music capture; disabled unless its environment variable is set.
[[patches.hook]]
func = "func_80006FE8"
before_vram = 0x80006FE8
text = "extern void stadiumfei_capture_music(uint8_t*, recomp_context*); stadiumfei_capture_music(rdram, ctx);"
'''

def main():
    p=argparse.ArgumentParser();p.add_argument('port',type=Path);a=p.parse_args()
    for name,addition in [('extras.c',HOOK),('game.toml',PATCH)]:
        path=a.port/name;text=path.read_text(encoding='utf-8')
        if 'stadiumfei_capture_music' not in text:path.write_text(text+addition,encoding='utf-8')
    # Existing generated sources are not regenerated by CMake. Apply the same
    # entry hook there, without recompiling every unaffected function group.
    marker='RECOMP_FUNC void func_80006FE8(uint8_t* rdram, recomp_context* ctx) {'
    for path in (a.port/'generated').glob('funcs_*.c'):
        text=path.read_text(encoding='utf-8')
        if marker in text and 'stadiumfei_capture_music' not in text:
            text=text.replace(marker,marker+'\n    extern void stadiumfei_capture_music(uint8_t*, recomp_context*);\n    stadiumfei_capture_music(rdram, ctx);',1)
            path.write_text(text,encoding='utf-8')
    print('Hook instalado. Compila el port; solo se activa durante Capturar-musica.ps1.')

if __name__=='__main__':main()
